analyzer:
  errors:
    use_build_context_synchronously: ignore
    deprecated_member_use: ignore
    avoid_web_libraries_in_flutter: ignore

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_web_libraries_in_flutter: false
    prefer_final_fields: true
    unnecessary_this: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
